project:
  type: website
  output-dir: docs

website:
  title: "warmup-rhys-tilford"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: trukdslajsd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



