project:
  type: website
  output-dir: docs

website:
  title: "personal-rhys-tilford"
  site-url: "https://rctilford.github.io/personal-rhys-tilford/"
  google-analytics: G-5R6TTB9D5X
  navbar:
    title: "<svg class='logo' viewbox='-60 -65 250 250'><path></path><circle id='c1'/><circle id='c2'/><circle id='c3'/></svg>"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Lore
      - href: articles/index.qmd
        text: Articles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/rhystilford
        target: _blank
      - icon: github
        href: https://github.com/rctilford
        target: _blank
  page-footer: 
    center: "<svg class='footer' viewbox='-790 -1245 1600 1245'><path></path></svg>"
    left: "<span class='name'>Rhys Tilford</span>"
    right: "<span class='copyright'>© 2023 - <script type='text/javascript'>document.write( new Date().getFullYear() );</script></span>"

  favicon: images/embosser.png
  back-to-top-navigation: true
  repo-url: https://github.com/rctilford/personal-rhys-tilford

format:
  html:
    theme:
      - custom.scss
      - pulse
    toc: true



