project:
  type: website
  output-dir: docs

website:
  title: "personal-rhys-tilford"
  site-url: "https://rctilford.github.io/personal-rhys-tilford/"
  google-analytics: G-5R6TTB9D5X
  navbar:
    title: "<svg class='logo'><path stroke-width='3'></path></svg>"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/rhystilford
        target: _blank
      - icon: github
        href: https://github.com/rctilford
        target: _blank
      - icon: instagram
        href: https://www.instagram.com/rctilford
        target: _blank
      - icon: spotify
        href: https://open.spotify.com/user/reesecupt?si=7f1c8e2d270d4a10
        target: _blank
  sidebar:
    - id: links
      title: "Articles"
      style: "docked"
      collapse-level: 2
      contents:
        - text: "Advent of Code 2022"
          href:  articles/article_01/index.qmd
        - text: "Sorting HTML Tables"
          href:  articles/article_02/index.qmd
        - text: "Cantor Set Presentation"
          href:  articles/article_03/index.qmd
        - text: "Tidying Unkempt Data"
          href:  articles/article_04/index.qmd
        - text: "Google Analytics Integration"
          href:  articles/article_05/index.qmd
  page-footer:
    background: light

  favicon: images/glamourshot.png
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/rctilford/personal-rhys-tilford
  repo-actions: issue

format:
  html:
    theme: 
      light: pulse
    css: styles.css
    toc: true



