project:
  type: website
  output-dir: docs

website:
  title: "personal-rhys-tilford"
  site-url: "https://rctilford.github.io/personal-rhys-tilford/"
  google-analytics: G-5R6TTB9D5X
  navbar:
    title: "<svg class='logo' viewbox='65 55 100 10'><path></path></svg>"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/rhystilford
        target: _blank
      - icon: github
        href: https://github.com/rctilford
        target: _blank
      - icon: instagram
        href: https://www.instagram.com/rctilford
        target: _blank
      - icon: spotify
        href: https://open.spotify.com/user/reesecupt?si=7f1c8e2d270d4a10
        target: _blank
  page-footer:
    background: light

  favicon: images/glamourshot.png
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/rctilford/personal-rhys-tilford
  repo-actions: issue

format:
  html:
    theme: 
      light: pulse
    css: styles.css
    toc: true



