project:
  type: website
  output-dir: docs

website:
  title: "warmup-rhys-tilford"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - sidebar:articles
  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      collapse-level: 2
      contents: 
        - text: "Advent of Code 2022"
          href:  articles/article_01.qmd
        - text: "Browser Implementation"
          href:  articles/article_02.qmd
  favicon: images/glamourshot.png
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/rctilford/warmup-rhys-tilford
  repo-actions: issue

format:
  html:
    theme: 
      dark: vapor
      light: lux
    css: styles.css
    toc: true



