project:
  type: website
  output-dir: docs

website:
  title: "personal-rhys-tilford"
  site-url: "https://rctilford.github.io/personal-rhys-tilford/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles
  sidebar:
    - id: links
      title: "Articles"
      style: "docked"
      collapse-level: 2
      contents:
        - text: "Advent of Code 2022"
          href:  articles/article_01/index.qmd
        - text: "Sorting HTML Tables"
          href:  articles/article_02/index.qmd
        - text: "Cantor Set Presentation"
          href: articles/article_03/index.qmd
  page-footer:
    background: light
    center:
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/rhystilford
        target: _blank
      - icon: github
        text: Github
        href: https://github.com/rctilford
        target: _blank
      - icon: instagram
        text: Instagram
        href: https://www.instagram.com/rctilford
        target: _blank
      - icon: spotify
        text: Spotify
        href: https://open.spotify.com/user/reesecupt?si=7f1c8e2d270d4a10
        target: _blank

  favicon: images/glamourshot.png
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/rctilford/personal-rhys-tilford
  repo-actions: issue

format:
  html:
    theme: 
      light: pulse
    css: styles.css
    toc: true



