project:
  type: website
  output-dir: docs

website:
  title: "warmup-rhys-tilford"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles 
  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      collapse-level: 2
      contents: 
        - text: "Advent of Code 2022"
          href:  articles/article_01.qmd
        - text: "Browser Implementation"
          href:  articles/article_02.qmd
  favicon: images/glamourshot.png

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



