---
title: Cantor Set Presentation
author: Rhys Tilford
description: Read my presentation of everything I have learned about the Cantor Set.
date: 11/8/2023
categories: [Education, Math]
---

### The Definition

> **11.1.10 Definition** The **Cantor set** $\mathbb{F}$ is the intersection of the sets $F_n,n\in\mathbb{N}$, obtained by successive removal of open middle thirds, starting with $[0,1]$.
>
> -- <cite>Intro to Real Analysis: Bartle and Sherbert (p. 331)</cite>

### Visualization

```{=html}
<script crossorigin src="https://unpkg.com/wolfram-notebook-embedder@0.3/dist/wolfram-notebook-embedder.min.js"></script>
```
::: {#WNE-div-fbd3d6af-86fb-4c0a-a478-71092d7c0437}
:::

```{=html}
<script>WolframNotebookEmbedder.embed("https://www.wolframcloud.com/obj/demonstrations/CantorSet-source.nb",document.getElementById("WNE-div-fbd3d6af-86fb-4c0a-a478-71092d7c0437"));</script>
```
::: callout-note
This visual is generated from the Wolfram Cloud: Use [this](https://www.wolframcloud.com/objects/demonstrations/CantorSet-source.nb) link to access it.
:::

### Proving Key Properties

##### Property 1: The total length of the removed intervals is 1

###### Proof:

We will construct a convergent geometric series of the lengths of the removed open middle thirds.

We see from the visual that the length of the removed open middle thirds is the series:

$$
\frac{1}{3}+\frac{2}{9}+\frac{4}{27}+\frac{8}{81}+...
$$

First, Let's work with the denominator:

$$
=\frac{1}{3^1}+\frac{2}{3^2}+\frac{4}{3^3}+\frac{8}{3^4}+...
$$

Now we can tackle the numerator: 

$$
=\frac{2^0}{3^1}+\frac{2^1}{3^2}+\frac{2^2}{3^3}+\frac{2^3}{3^4}+...
$$

Now we have what we need to build a series: 

$$
=\sum_{i=0}^{\infty}{\frac{2^i}{3^{(i+1)}}}
$$

This isn't quite a geometric series though. We'll do some quick mathematical yassification to remedy this. We start by rewriting the denominator with exponent rules: 

$$
=\sum_{i=0}^{\infty}{\frac{2^i}{3*3^i}}
$$

Now we can pull the constant multiple outside the sum: 

$$
=\frac{1}{3}*\sum_{i=0}^{\infty}{\Bigl(\frac{2}{3}\Bigr)^i}
$$

Next we will apply the formula for the sum of a geometric series: 

$$
=\frac{1}{3}*\frac{1}{1-\frac{2}{3}}
$$

With some simplification we find that the sum is infact $1$: 

$$
=\frac{1}{3}*\frac{1}{\frac{1}{3}}=\frac{3}{3}=1
$$

$\mathfrak{Here}$ $\mathfrak{Endeth}$ $\mathfrak{The}$ $\mathfrak{Proofeth}$

##### Property 2: The Cantor set $\mathbb{F}$ contains no nonempty open interval as a subset

###### Proof:

For this proof we will use contradiction. We assume $\mathbb{F}$ contains a nonempty open interval. Well, we obtain each element in $\mathbb{F}$ by removing *open* intervals. This means that the remaining intervals in each element of $\mathbb{F}$ must be *closed*. So there can never be a nonempty open interval in $\mathbb{F}$.

##### Property 3: The Cantor set $\mathbb{F}$ has infinitely (even uncountably) many points

###### Proof:





Q.E.D. (Queer Educational Demonstration)